language: erlang
install: true
before_script:
  - wget https://s3.amazonaws.com/rebar3/rebar3
  - chmod +x rebar3
env:
  - PATH=".:$PATH"
script:
  - ./rebar3 as dev compile
  - ./rebar3 as test eunit
notifications:
  recipients:
    - oubiwann@gmail.com
otp_release:
  - 19.2
  - 18.3
